@extends('layouts.app')
@section('content')
<h1 class="mb-5 text-2xl font-bold">New Stock Adjustment</h1>
<form method="POST" action="{{ route('stock_adjustments.store') }}" x-data="{rows:[{product_id:'',qty:'',unit:'pcs',unit_cost:'',direction:'in',notes:''}]}" class="space-y-5">@csrf
<div class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-3"><label>Warehouse<select name="warehouse_id" required class="mt-1 w-full rounded border px-3 py-2">@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></label><label>Date<input type="date" name="adjustment_date" value="{{ now()->format('Y-m-d') }}" required class="mt-1 w-full rounded border px-3 py-2"></label><label>Reason<input name="reason" required class="mt-1 w-full rounded border px-3 py-2" placeholder="Damage, correction, opening stock..."></label><label class="md:col-span-3">Notes<textarea name="notes" rows="2" class="mt-1 w-full rounded border px-3 py-2"></textarea></label></div>
<div class="rounded-xl border bg-white p-5"><div class="mb-3 flex items-center justify-between"><h2 class="font-bold">Items (max 15)</h2><button type="button" @click="if(rows.length<15) rows.push({product_id:'',qty:'',unit:'pcs',unit_cost:'',direction:'in',notes:''})" class="rounded border px-3 py-1 text-sm">+ Add</button></div><div class="space-y-3"><template x-for="(row,i) in rows" :key="i"><div class="grid gap-2 rounded-lg border p-3 md:grid-cols-6"><select :name="`items[${i}][product_id]`" x-model="row.product_id" required class="rounded border px-2 py-2"><option value="">Product</option>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }}{{ $p->sku ? ' ('.$p->sku.')' : '' }}</option>@endforeach</select><input :name="`items[${i}][qty]`" x-model="row.qty" type="number" step="0.001" min="0.001" required placeholder="Qty" class="rounded border px-2 py-2"><input :name="`items[${i}][unit]`" x-model="row.unit" required placeholder="Unit" class="rounded border px-2 py-2"><input :name="`items[${i}][unit_cost]`" x-model="row.unit_cost" type="number" step="0.01" min="0" required placeholder="Unit cost" class="rounded border px-2 py-2"><select :name="`items[${i}][direction]`" x-model="row.direction" class="rounded border px-2 py-2"><option value="in">Stock In</option><option value="out">Stock Out</option></select><div class="flex gap-2"><input :name="`items[${i}][notes]`" x-model="row.notes" placeholder="Line note" class="min-w-0 flex-1 rounded border px-2 py-2"><button type="button" @click="rows.splice(i,1)" x-show="rows.length>1" class="rounded border px-3 text-red-700">×</button></div></div></template></div></div>
<div class="flex justify-end gap-2"><a href="{{ route('stock_adjustments.index') }}" class="rounded-lg border px-4 py-2">Cancel</a><button class="rounded-lg bg-gray-900 px-5 py-2 font-semibold text-white">Post Adjustment</button></div>
</form>
@endsection
