@extends('layouts.app')
@section('content')
<h1 class="text-2xl font-bold">New Supplier Payment</h1><p class="mb-5 text-sm text-gray-500">Record a payment and optionally allocate it to outstanding purchases.</p>
@if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('supplier_payments.store') }}" x-data="supplierPaymentForm()" class="space-y-5">@csrf
<div class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-3">
<label>Supplier<select name="supplier_id" x-model="supplierId" @change="loadPurchases" required class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->company_name }}</option>@endforeach</select></label>
<label>Payment Date<input type="date" name="payment_date" value="{{ old('payment_date',date('Y-m-d')) }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></label>
<label>Amount (PKR)<input type="number" step="0.01" min="0.01" name="amount" x-model.number="amount" required class="mt-1 w-full rounded-lg border px-3 py-2"></label>
<label>Payment Method<select name="payment_method" class="mt-1 w-full rounded-lg border px-3 py-2">@foreach(['Cash','Bank Transfer','Cheque','Card','Online','Other'] as $method)<option>{{ $method }}</option>@endforeach</select></label>
<label>Reference<input name="reference" value="{{ old('reference') }}" class="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Cheque no., bank ref, etc."></label>
<label>Notes<input name="notes" value="{{ old('notes') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label>
</div>
<div class="rounded-xl border bg-white p-5"><div class="mb-3 flex justify-between"><h2 class="font-semibold">Allocate to Purchases</h2><span class="text-sm text-gray-500">Allocated: PKR <span x-text="allocated.toFixed(2)"></span></span></div>
<div x-show="loading" class="text-sm text-gray-500">Loading outstanding purchases…</div><div x-show="!loading && supplierId && purchases.length === 0" class="text-sm text-gray-500">No outstanding purchases. The payment can remain an advance/unallocated amount.</div>
<div class="overflow-x-auto" x-show="purchases.length"><table class="min-w-full text-sm"><thead><tr class="border-b"><th class="p-2 text-left">Purchase</th><th class="p-2 text-left">Date</th><th class="p-2 text-right">Outstanding</th><th class="p-2 text-right">Allocate</th></tr></thead><tbody><template x-for="purchase in purchases" :key="purchase.id"><tr class="border-b"><td class="p-2" x-text="purchase.purchase_number"></td><td class="p-2" x-text="purchase.purchase_date"></td><td class="p-2 text-right" x-text="'PKR ' + Number(purchase.outstanding).toFixed(2)"></td><td class="p-2 text-right"><input type="hidden" :disabled="!(Number(purchase.allocate)>0)" :name="`allocations[${purchase.id}][purchase_id]`" :value="purchase.id"><input type="number" min="0" step="0.01" :disabled="!(Number(purchase.allocate)>0)" :max="Math.min(purchase.outstanding, Math.max(0, amount - allocated + current(purchase.id)))" :name="`allocations[${purchase.id}][amount]`" x-model.number="purchase.allocate" @input="normalize(purchase)" class="w-36 rounded border px-2 py-1 text-right"></td></tr></template></tbody></table></div></div>
<div class="flex justify-end gap-2"><a href="{{ route('supplier_payments.index') }}" class="rounded-lg border px-4 py-2">Cancel</a><button class="rounded-lg bg-black px-5 py-2 text-white">Post Payment</button></div></form>
<script>function supplierPaymentForm(){return{supplierId:'',amount:0,purchases:[],loading:false,get allocated(){return this.purchases.reduce((s,p)=>s+(Number(p.allocate)||0),0)},async loadPurchases(){this.purchases=[];if(!this.supplierId)return;this.loading=true;try{this.purchases=await fetch('{{ url('/suppliers') }}/'+this.supplierId+'/outstanding-purchases').then(r=>r.json())}finally{this.loading=false}},current(id){let p=this.purchases.find(x=>x.id===id);return p?Number(p.allocate)||0:0},normalize(p){p.allocate=Math.max(0,Math.min(Number(p.outstanding)||0,Number(p.allocate)||0,Number(this.amount)||0));if(this.allocated>(Number(this.amount)||0))p.allocate=Math.max(0,p.allocate-(this.allocated-Number(this.amount)))}}}</script>
@endsection
