@extends('layouts.app')
@section('content')
<div class="max-w-6xl mx-auto space-y-5"><div><h1 class="text-2xl font-bold">Receive Purchase</h1><p class="text-sm text-gray-500">Receiving a purchase immediately adds the items to Main Warehouse stock.</p></div>
@if($errors->any())<div class="rounded bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('purchases.store') }}" class="space-y-5">@csrf
<div class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-4"><div><label class="text-sm font-medium">Supplier</label><select name="supplier_id" required class="mt-1 w-full rounded border px-3 py-2"><option value="">Select</option>@foreach($suppliers as $s)<option value="{{ $s->id }}">{{ $s->company_name }}</option>@endforeach</select></div><div><label class="text-sm font-medium">Warehouse</label><select name="warehouse_id" required class="mt-1 w-full rounded border px-3 py-2">@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div><label class="text-sm font-medium">Purchase Date</label><input type="date" name="purchase_date" value="{{ now()->toDateString() }}" required class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Supplier Invoice #</label><input name="supplier_invoice_number" class="mt-1 w-full rounded border px-3 py-2"></div></div>
<div class="overflow-x-auto rounded-xl border bg-white"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3">#</th><th class="p-3">Product</th><th class="p-3">Description</th><th class="p-3">Qty</th><th class="p-3">Unit Cost</th><th class="p-3">Tax %</th><th class="p-3">Serial #</th></tr></thead><tbody>@for($i=0;$i<15;$i++)<tr class="border-t"><td class="p-2">{{ $i+1 }}</td><td class="p-2"><select name="items[{{ $i }}][product_id]" class="w-44 rounded border px-2 py-2" {{ $i===0?'required':'' }}><option value="">{{ $i===0?'Select product':'Optional' }}</option>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></td><td class="p-2"><input name="items[{{ $i }}][description]" class="w-56 rounded border px-2 py-2" {{ $i===0?'required':'' }}></td><td class="p-2"><input name="items[{{ $i }}][quantity]" type="number" step="0.0001" min="0" class="w-24 rounded border px-2 py-2" {{ $i===0?'required':'' }}></td><td class="p-2"><input name="items[{{ $i }}][unit_cost]" type="number" step="0.01" min="0" class="w-28 rounded border px-2 py-2" {{ $i===0?'required':'' }}></td><td class="p-2"><input name="items[{{ $i }}][tax_rate]" type="number" step="0.001" min="0" value="0" class="w-20 rounded border px-2 py-2"></td><td class="p-2"><input name="items[{{ $i }}][serial_number]" class="w-36 rounded border px-2 py-2"></td><input type="hidden" name="items[{{ $i }}][unit]" value="Unit"></tr>@endfor</tbody></table></div>
<div class="rounded-xl border bg-white p-5"><label class="text-sm font-medium">Notes</label><textarea name="notes" rows="3" class="mt-1 w-full rounded border px-3 py-2"></textarea></div><div class="flex justify-end"><button class="rounded bg-gray-900 px-5 py-2.5 font-bold text-white">Receive Purchase</button></div></form></div>
@endsection
