@extends('layouts.app')
@section('content')
<div class="mb-5"><h1 class="text-2xl font-bold">Edit User</h1><p class="text-sm text-gray-500">Update access, role, or reset the password.</p></div>
@if($errors->any())<div class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('users.update',$user) }}" class="max-w-2xl space-y-4 rounded-xl border bg-white p-5">@csrf @method('PUT')
<div class="grid gap-4 md:grid-cols-2"><div><label class="text-sm font-medium">Name</label><input name="name" value="{{ old('name',$user->name) }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></div><div><label class="text-sm font-medium">Email</label><input name="email" type="email" value="{{ old('email',$user->email) }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></div><div><label class="text-sm font-medium">Role</label><select name="role" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="staff" @selected(old('role',$user->role)==='staff')>Staff</option><option value="admin" @selected(old('role',$user->role)==='admin')>Admin</option></select></div><div><label class="text-sm font-medium">New Password</label><input name="password" type="password" minlength="8" class="mt-1 w-full rounded-lg border px-3 py-2"><p class="mt-1 text-xs text-gray-500">Leave blank to keep the current password.</p></div><div><label class="text-sm font-medium">Confirm New Password</label><input name="password_confirmation" type="password" minlength="8" class="mt-1 w-full rounded-lg border px-3 py-2"></div></div>
<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$user->is_active))> Active</label>
<div class="flex gap-2"><button class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Save Changes</button><a href="{{ route('users.index') }}" class="rounded-lg border px-4 py-2 text-sm">Cancel</a></div></form>
@endsection
