<?php

use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerPaymentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeliveryChallanController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\MasterDataController;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\StockAdjustmentController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\SupplierPaymentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.store');
});

Route::middleware(['auth', 'active.user'])->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/quotations', [QuotationController::class, 'index'])->name('quotations.index');
    Route::get('/quotations/create', [QuotationController::class, 'create'])->name('quotations.create');
    Route::post('/quotations', [QuotationController::class, 'store'])->name('quotations.store');
    Route::get('/quotations/{quotation}', [QuotationController::class, 'show'])->name('quotations.show');
    Route::get('/quotations/{quotation}/edit', [QuotationController::class, 'edit'])->name('quotations.edit');
    Route::put('/quotations/{quotation}', [QuotationController::class, 'update'])->name('quotations.update');
    Route::get('/quotations/{quotation}/print', [QuotationController::class, 'print'])->name('quotations.print');
    Route::get('/quotations/{quotation}/invoice', [InvoiceController::class, 'createFromQuotation'])->name('invoices.createFromQuotation');
    Route::post('/quotations/{quotation}/invoice', [InvoiceController::class, 'storeFromQuotation'])->name('invoices.storeFromQuotation');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/invoices/{invoice}/print', [InvoiceController::class, 'print'])->name('invoices.print');
    Route::get('/invoices/{invoice}/delivery-challan', [DeliveryChallanController::class, 'createFromInvoice'])->name('delivery_challans.createFromInvoice');
    Route::post('/invoices/{invoice}/delivery-challan', [DeliveryChallanController::class, 'storeFromInvoice'])->name('delivery_challans.storeFromInvoice');
    Route::get('/delivery-challans', [DeliveryChallanController::class, 'index'])->name('delivery_challans.index');
    Route::get('/delivery-challans/{deliveryChallan}', [DeliveryChallanController::class, 'show'])->name('delivery_challans.show');
    Route::get('/delivery-challans/{deliveryChallan}/print', [DeliveryChallanController::class, 'print'])->name('delivery_challans.print');
    Route::get('/purchases', [PurchaseController::class, 'index'])->name('purchases.index');
    Route::get('/purchases/create', [PurchaseController::class, 'create'])->name('purchases.create');
    Route::post('/purchases', [PurchaseController::class, 'store'])->name('purchases.store');
    Route::get('/purchases/{purchase}', [PurchaseController::class, 'show'])->name('purchases.show');
    Route::get('/customer-payments', [CustomerPaymentController::class, 'index'])->name('customer_payments.index');
    Route::get('/customer-payments/create', [CustomerPaymentController::class, 'create'])->name('customer_payments.create');
    Route::post('/customer-payments', [CustomerPaymentController::class, 'store'])->name('customer_payments.store');
    Route::get('/customer-payments/{payment}', [CustomerPaymentController::class, 'show'])->name('customer_payments.show');
    Route::get('/customer-payments/{payment}/print', [CustomerPaymentController::class, 'print'])->name('customer_payments.print');
    Route::get('/receivables', [CustomerPaymentController::class, 'receivables'])->name('receivables.index');
    Route::get('/customers/{customer}/outstanding-invoices', [CustomerPaymentController::class, 'invoices'])->name('customers.outstandingInvoices');
    Route::get('/customers/{customer}/statement', [CustomerPaymentController::class, 'statement'])->name('customer_payments.statement');
    Route::get('/supplier-payments', [SupplierPaymentController::class, 'index'])->name('supplier_payments.index');
    Route::get('/supplier-payments/create', [SupplierPaymentController::class, 'create'])->name('supplier_payments.create');
    Route::post('/supplier-payments', [SupplierPaymentController::class, 'store'])->name('supplier_payments.store');
    Route::get('/supplier-payments/{payment}', [SupplierPaymentController::class, 'show'])->name('supplier_payments.show');
    Route::get('/supplier-payments/{payment}/print', [SupplierPaymentController::class, 'print'])->name('supplier_payments.print');
    Route::get('/payables', [SupplierPaymentController::class, 'payables'])->name('payables.index');
    Route::get('/suppliers/{supplier}/outstanding-purchases', [SupplierPaymentController::class, 'purchases'])->name('suppliers.outstandingPurchases');
    Route::get('/suppliers/{supplier}/statement', [SupplierPaymentController::class, 'statement'])->name('supplier_payments.statement');
    Route::get('/customers', [PartyController::class, 'customers'])->name('parties.customers');
    Route::get('/customers/create', [PartyController::class, 'createCustomer'])->name('parties.customer_create');
    Route::post('/customers', [PartyController::class, 'storeCustomer'])->name('parties.customer_store');
    Route::get('/customers/{customer}/edit', [PartyController::class, 'editCustomer'])->name('parties.customer_edit');
    Route::put('/customers/{customer}', [PartyController::class, 'updateCustomer'])->name('parties.customer_update');
    Route::get('/suppliers', [PartyController::class, 'suppliers'])->name('parties.suppliers');
    Route::get('/suppliers/create', [PartyController::class, 'createSupplier'])->name('parties.supplier_create');
    Route::post('/suppliers', [PartyController::class, 'storeSupplier'])->name('parties.supplier_store');
    Route::get('/suppliers/{supplier}/edit', [PartyController::class, 'editSupplier'])->name('parties.supplier_edit');
    Route::put('/suppliers/{supplier}', [PartyController::class, 'updateSupplier'])->name('parties.supplier_update');
    Route::get('/products', [ProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->name('products.edit');
    Route::put('/products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::get('/stock', [StockController::class, 'index'])->name('stock.index');
    Route::get('/stock/{product}/ledger', [StockController::class, 'ledger'])->name('stock.ledger');
    Route::get('/stock-adjustments', [StockAdjustmentController::class, 'index'])->name('stock_adjustments.index');
    Route::get('/stock-adjustments/create', [StockAdjustmentController::class, 'create'])->name('stock_adjustments.create');
    Route::post('/stock-adjustments', [StockAdjustmentController::class, 'store'])->name('stock_adjustments.store');
    Route::get('/stock-adjustments/{stockAdjustment}', [StockAdjustmentController::class, 'show'])->name('stock_adjustments.show');
    Route::middleware('role:admin')->group(function () {
        Route::get('/users', [UserController::class, 'index'])->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->name('users.store');
        Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
        Route::patch('/users/{user}/toggle', [UserController::class, 'toggleActive'])->name('users.toggle');
        Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit_logs.index');
        Route::get('/audit-logs/{auditLog}', [AuditLogController::class, 'show'])->name('audit_logs.show');
        Route::get('/master-data', [MasterDataController::class, 'index'])->name('master_data.index');
        Route::post('/master-data/categories', [MasterDataController::class, 'storeCategory'])->name('master_data.categories.store');
        Route::put('/master-data/categories/{category}', [MasterDataController::class, 'updateCategory'])->name('master_data.categories.update');
        Route::post('/master-data/units', [MasterDataController::class, 'storeUnit'])->name('master_data.units.store');
        Route::put('/master-data/units/{unit}', [MasterDataController::class, 'updateUnit'])->name('master_data.units.update');
    });
});
