@extends('layouts.app')
@section('content')
<div data-quotation>
<form data-save-form method="POST" action="{{ route('quotations.store') }}">
@csrf
<div class="mb-5 flex flex-wrap items-end justify-between gap-3">
 <div><div class="text-sm text-gray-500">Sales</div><h1 class="text-2xl font-bold">New Quotation</h1></div>
 <div class="text-right"><div class="text-xs uppercase tracking-wide text-gray-500">Quotation</div><div class="text-xl font-bold">QTN-DRAFT</div></div>
</div>
<div class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2">
 <label class="text-sm font-semibold">Customer<select name="customer_id" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Select customer</option>@foreach($customers as $c)<option value="{{ $c->id }}">{{ $c->company_name }}</option>@endforeach</select></label>
 <label class="text-sm font-semibold">Date<input name="quote_date" type="date" value="{{ date('Y-m-d') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label>
 <label class="text-sm font-semibold">Reference<input name="reference" class="mt-1 w-full rounded-lg border px-3 py-2" placeholder="PKTL - RWD - IT / PO / PR"></label>
 <label class="text-sm font-semibold">Summary<input name="summary" class="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Supply of Computer Hardware"></label>
</div>
<div class="mt-4 overflow-hidden rounded-xl border bg-white">
 <div class="flex items-center justify-between border-b p-4"><h2 class="font-bold">Items</h2><button type="button" data-add-item class="rounded-lg bg-green-700 px-3 py-2 text-sm font-bold text-white">+ Add Item</button></div>
 <div class="overflow-x-auto"><table class="min-w-[1000px] w-full text-sm"><thead class="bg-gray-50 text-left"><tr><th class="p-3">#</th><th class="p-3">Description</th><th class="p-3">Qty</th><th class="p-3">Purchase Cost</th><th class="p-3">Delivery</th><th class="p-3">Other</th><th class="p-3">Selling Price</th><th class="p-3">Discount</th><th class="p-3">Tax %</th><th class="p-3">Total</th><th></th></tr></thead><tbody data-items-body>
<tr data-item class="border-t"><td class="p-2">1</td><td class="p-2"><input name="items[0][description]" class="w-64 rounded border px-2 py-2" value="New Wi-Fi Router (Model: TP-Link Archer C20)" required></td><td class="p-2"><input data-qty name="items[0][quantity]" type="number" step="0.01" value="1" class="w-20 rounded border px-2 py-2"></td><td class="p-2"><input data-purchase name="items[0][purchase_cost]" type="number" step="0.01" value="7500" class="w-28 rounded border px-2 py-2"></td><td class="p-2"><input data-delivery name="items[0][delivery_cost]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-other name="items[0][other_cost]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-selling name="items[0][selling_price]" type="number" step="0.01" value="9750" class="w-28 rounded border px-2 py-2"></td><td class="p-2"><input data-discount name="items[0][discount]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-tax name="items[0][tax_rate]" type="number" step="0.01" value="0" class="w-20 rounded border px-2 py-2"></td><td data-line-total class="p-2 font-semibold">9,750.00</td><td class="p-2"><button type="button" data-remove-item class="text-red-600">×</button></td></tr>
</tbody></table></div>
</div>
<div class="mt-4 grid gap-4 lg:grid-cols-[1fr_360px]">
 <div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Terms & Conditions</h2><textarea name="terms" rows="7" class="mt-3 w-full rounded-lg border px-3 py-2">(1) The above mentioned prices are inclusive of applicable withholding tax.&#10;(2) The above mentioned prices are non G.S.T.&#10;(3) This quotation is valid for Seven (7) working days.&#10;(4) Used / Imported hardware items are provided on Check Warranty basis.&#10;(5) All items shall be delivered within Three (3) working days after issuance of Purchase Order.</textarea></div>
 <div class="rounded-xl border bg-white p-5"><h2 class="font-bold">Estimated Profit</h2><dl class="mt-4 space-y-2 text-sm"><div class="flex justify-between"><dt>Total Cost</dt><dd data-total-cost>0.00</dd></div><div class="flex justify-between"><dt>Selling Value</dt><dd data-selling-total>0.00</dd></div><div class="flex justify-between"><dt>Tax</dt><dd data-tax-total>0.00</dd></div><div class="my-3 border-t"></div><div class="flex justify-between text-lg font-bold"><dt>Customer Total</dt><dd data-grand-total>0.00</dd></div><div class="flex justify-between text-lg font-bold text-green-700"><dt>Estimated Profit</dt><dd data-profit>0.00</dd></div><div class="flex justify-between font-semibold"><dt>Margin</dt><dd data-margin>0.00%</dd></div></dl><button class="mt-5 w-full rounded-lg bg-green-700 px-4 py-3 font-bold text-white" type="submit">Save Quotation</button></div>
</div>
</form>
<template id="quotation-row-template"><tr data-item class="border-t"><td class="p-2">__INDEX__</td><td class="p-2"><input name="items[__INDEX0__][description]" class="w-64 rounded border px-2 py-2" required></td><td class="p-2"><input data-qty name="items[__INDEX0__][quantity]" type="number" step="0.01" value="1" class="w-20 rounded border px-2 py-2"></td><td class="p-2"><input data-purchase name="items[__INDEX0__][purchase_cost]" type="number" step="0.01" value="0" class="w-28 rounded border px-2 py-2"></td><td class="p-2"><input data-delivery name="items[__INDEX0__][delivery_cost]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-other name="items[__INDEX0__][other_cost]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-selling name="items[__INDEX0__][selling_price]" type="number" step="0.01" value="0" class="w-28 rounded border px-2 py-2"></td><td class="p-2"><input data-discount name="items[__INDEX0__][discount]" type="number" step="0.01" value="0" class="w-24 rounded border px-2 py-2"></td><td class="p-2"><input data-tax name="items[__INDEX0__][tax_rate]" type="number" step="0.01" value="0" class="w-20 rounded border px-2 py-2"></td><td data-line-total class="p-2 font-semibold">0.00</td><td class="p-2"><button type="button" data-remove-item class="text-red-600">×</button></td></tr></template>
</div>
@endsection
