<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $quotation->quotation_number }}</title>
<style>
*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#111;margin:0;background:#f3f4f6;font-size:13px;line-height:1.45}.sheet{max-width:900px;margin:24px auto;background:#fff;padding:34px 38px;min-height:1100px}.actions{margin-bottom:18px;display:flex;gap:8px}.actions button{border:0;background:#111827;color:#fff;padding:9px 16px;border-radius:5px;cursor:pointer}.header{display:flex;justify-content:space-between;gap:30px;border-bottom:2px solid #111;padding-bottom:18px}.company{font-size:20px;font-weight:700}.doc-title{text-align:right;font-size:24px;font-weight:700}.doc-no{font-size:13px;margin-top:4px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin:22px 0}.label{font-size:11px;text-transform:uppercase;color:#555;font-weight:700}.box{border:1px solid #ddd;padding:12px;min-height:92px}.items{width:100%;border-collapse:collapse;margin-top:10px}.items th,.items td{border:1px solid #bbb;padding:8px}.items th{background:#f1f1f1;font-size:12px}.right{text-align:right}.totals{width:310px;margin:18px 0 0 auto}.totals div{display:flex;justify-content:space-between;padding:3px 0}.grand{border-top:2px solid #111;margin-top:6px;padding-top:7px!important;font-size:15px;font-weight:700}.terms{margin-top:32px;border-top:1px solid #ccc;padding-top:14px}.sign{margin-top:75px;text-align:right}.sign span{display:inline-block;border-top:1px solid #111;padding:8px 45px 0}.muted{color:#555}@media(max-width:650px){body{background:#fff}.sheet{margin:0;padding:20px;min-height:0}.meta{grid-template-columns:1fr}.header{flex-direction:column}.doc-title{text-align:left}.totals{width:100%}.items{font-size:11px}.items th,.items td{padding:5px}}@media print{body{background:#fff}.sheet{margin:0;padding:12mm;max-width:none;min-height:0}.actions{display:none}@page{size:A4;margin:8mm}}
</style>
</head>
<body><div class="sheet">
<div class="actions"><button onclick="window.print()">Print</button><button onclick="history.back()">Back</button></div>
<header class="header"><div><div class="company">IT Supplies, Services & Support</div><div class="muted">Quotation</div></div><div class="doc-title">QUOTATION<div class="doc-no">{{ $quotation->quotation_number }}</div></div></header>
<div class="meta"><div class="box"><div class="label">Customer</div><strong>{{ $quotation->customer->company_name }}</strong><br>{!! nl2br(e($quotation->customer->address)) !!}<br>{{ $quotation->customer->phone ?: $quotation->customer->mobile }}</div><div class="box"><div><span class="label">Date</span> {{ $quotation->quote_date?->format('d-M-Y') }}</div><div><span class="label">Valid Until</span> {{ $quotation->valid_until?->format('d-M-Y') ?? '—' }}</div><div><span class="label">Reference</span> {{ $quotation->reference ?: '—' }}</div><div><span class="label">Summary</span> {{ $quotation->summary ?: '—' }}</div></div></div>
<table class="items"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th class="right">Unit Price (PKR)</th><th class="right">Amount (PKR)</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $item->line_no }}</td><td>{{ $item->description }}</td><td>{{ rtrim(rtrim(number_format($item->quantity,4,'.',''),'0'),'.') }} {{ $item->unit }}</td><td class="right">{{ number_format($item->selling_price,2) }}</td><td class="right">{{ number_format(($item->selling_price*$item->quantity)-$item->discount+$item->tax_amount,2) }}</td></tr>@endforeach</tbody></table>
<div class="totals"><div><span>Subtotal</span><span>{{ number_format($quotation->subtotal,2) }}</span></div><div><span>Discount</span><span>{{ number_format($quotation->discount_total,2) }}</span></div><div><span>Tax</span><span>{{ number_format($quotation->tax_total,2) }}</span></div><div class="grand"><span>Total PKR</span><span>{{ number_format($quotation->total_amount,2) }}</span></div></div>
@if($quotation->terms)<div class="terms"><strong>Terms & Conditions</strong><div>{!! nl2br(e($quotation->terms)) !!}</div></div>@endif
<div class="sign"><span>Authorized Signature</span></div>
</div></body></html>
