@extends('layouts.app')
@section('content')
<h1 class="text-2xl font-bold">New Product / Service</h1><p class="mb-5 text-sm text-gray-500">Create an item for quotations, purchases and stock.</p>
@if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('products.store') }}" class="space-y-5">@csrf
<div class="grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-3">
<label>SKU<input name="sku" value="{{ old('sku') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label><label>Name<input name="name" value="{{ old('name') }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></label><label>Type<select name="item_type" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="product">Product</option><option value="service">Service</option></select></label>
<label>Category<select name="product_category_id" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">None</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Unit<select name="unit_id" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">None</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}</option>@endforeach</select></label><label>Tax Rate %<input type="number" step="0.001" min="0" name="tax_rate" value="{{ old('tax_rate',0) }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label>
<label>Brand<input name="brand" value="{{ old('brand') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label><label>Model<input name="model" value="{{ old('model') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label><label>Warranty<input name="warranty" value="{{ old('warranty') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label>
<label>Purchase Cost<input type="number" step="0.01" min="0" name="purchase_cost" value="{{ old('purchase_cost',0) }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label><label>Default Selling Price<input type="number" step="0.01" min="0" name="default_selling_price" value="{{ old('default_selling_price',0) }}" class="mt-1 w-full rounded-lg border px-3 py-2"></label><label class="flex items-end gap-2 pb-2"><input type="checkbox" name="track_serial" value="1"> Track serial numbers</label>
<label class="md:col-span-3">Description<textarea name="description" rows="3" class="mt-1 w-full rounded-lg border px-3 py-2">{{ old('description') }}</textarea></label>
</div><div class="flex justify-end gap-2"><a href="{{ route('products.index') }}" class="rounded-lg border px-4 py-2">Cancel</a><button class="rounded-lg bg-black px-5 py-2 text-white">Save Product</button></div></form>
@endsection
