@extends('layouts.app')
@section('content')
<div class="max-w-6xl mx-auto space-y-5">
@if(session('success'))<div class="rounded bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif
<div class="flex items-center justify-between"><div><h1 class="text-2xl font-bold">{{ $invoice->invoice_number }}</h1><p class="text-sm text-gray-500">{{ $invoice->customer->company_name }}</p></div><a class="rounded border px-4 py-2" href="{{ route('invoices.print',$invoice) }}" target="_blank">Print</a></div>
<div class="grid gap-4 rounded border bg-white p-5 md:grid-cols-4 text-sm"><div><b>Date</b><div>{{ $invoice->invoice_date?->format('d-m-Y') }}</div></div><div><b>Reference</b><div>{{ $invoice->reference ?: '—' }}</div></div><div><b>Quotation</b><div>{{ $invoice->quotation?->quotation_number ?: '—' }}</div></div><div><b>Status</b><div>{{ ucfirst($invoice->status) }}</div></div></div>
<div class="overflow-x-auto rounded border bg-white"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">#</th><th class="p-3 text-left">Description</th><th class="p-3 text-right">Qty</th><th class="p-3 text-right">Selling</th><th class="p-3 text-right">Actual Cost</th><th class="p-3 text-right">Actual Profit</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr class="border-t"><td class="p-3">{{ $item->line_no }}</td><td class="p-3">{{ $item->description }}</td><td class="p-3 text-right">{{ rtrim(rtrim(number_format($item->quantity,4,'.',''), '0'), '.') }} {{ $item->unit }}</td><td class="p-3 text-right">PKR {{ number_format($item->selling_price_unit,2) }}</td><td class="p-3 text-right">PKR {{ number_format($item->actual_cost_unit,2) }}</td><td class="p-3 text-right">PKR {{ number_format($item->actual_profit,2) }}</td></tr>@endforeach</tbody></table></div>
<div class="ml-auto max-w-sm rounded border bg-white p-5 text-sm space-y-2"><div class="flex justify-between"><span>Subtotal</span><span>PKR {{ number_format($invoice->subtotal,2) }}</span></div><div class="flex justify-between"><span>Discount</span><span>PKR {{ number_format($invoice->discount_total,2) }}</span></div><div class="flex justify-between"><span>Tax</span><span>PKR {{ number_format($invoice->tax_total,2) }}</span></div><div class="flex justify-between border-t pt-2 font-bold"><span>Total</span><span>PKR {{ number_format($invoice->total_amount,2) }}</span></div><div class="flex justify-between border-t pt-2"><span>Actual Cost</span><span>PKR {{ number_format($invoice->actual_cost_total,2) }}</span></div><div class="flex justify-between font-bold"><span>Actual Profit</span><span>PKR {{ number_format($invoice->actual_profit,2) }}</span></div><div class="flex justify-between"><span>Margin</span><span>{{ number_format($invoice->actual_margin_percent,2) }}%</span></div></div>
</div>
@endsection
