@extends('layouts.app')
@section('content')
<div class="max-w-6xl mx-auto space-y-5">
<div><h1 class="text-2xl font-bold">Create Delivery Challan</h1><p class="text-sm text-gray-500">From invoice {{ $invoice->invoice_number }}</p></div>
@if($errors->any())<div class="rounded bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('delivery_challans.storeFromInvoice',$invoice) }}" class="space-y-5">@csrf
<div class="grid gap-4 rounded border bg-white p-5 md:grid-cols-3"><div><label class="text-sm font-medium">Challan Date</label><input required type="date" name="challan_date" value="{{ old('challan_date',now()->toDateString()) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Delivery Date</label><input type="date" name="delivery_date" value="{{ old('delivery_date',now()->toDateString()) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Shipped Date</label><input type="date" name="shipped_date" value="{{ old('shipped_date') }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Delivery Challan For</label><input name="delivery_challan_for" value="{{ old('delivery_challan_for',$invoice->summary) }}" class="mt-1 w-full rounded border px-3 py-2"></div><div><label class="text-sm font-medium">Shipping To</label><input name="shipping_to" value="{{ old('shipping_to',$invoice->customer->address) }}" class="mt-1 w-full rounded border px-3 py-2"></div></div>
<div class="overflow-x-auto rounded border bg-white"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3">#</th><th class="p-3 text-left">Item</th><th class="p-3">Invoice Qty</th><th class="p-3">Available / Deliver</th><th class="p-3">Serial #</th></tr></thead><tbody>@foreach($invoice->items as $i=>$item)<tr class="border-t"><td class="p-3">{{ $i+1 }}</td><td class="p-3">{{ $item->description }}</td><td class="p-3 text-center">{{ $item->quantity }} {{ $item->unit }}</td><td class="p-3"><input required min="0.0001" max="{{ $item->quantity }}" step="0.0001" type="number" name="items[{{ $i }}][quantity]" value="{{ old("items.$i.quantity",$item->quantity) }}" class="w-32 rounded border px-2 py-2"></td><td class="p-3"><input name="items[{{ $i }}][serial_number]" value="{{ old("items.$i.serial_number") }}" class="w-44 rounded border px-2 py-2"></td></tr>@endforeach</tbody></table></div>
<div class="rounded border bg-white p-5"><label class="text-sm font-medium">Terms & Conditions</label><textarea name="terms" rows="5" class="mt-1 w-full rounded border px-3 py-2">{{ old('terms') }}</textarea></div>
<div class="flex justify-end"><button class="rounded bg-gray-900 px-5 py-2.5 font-bold text-white">Create Delivery Challan</button></div></form></div>
@endsection
